- name: Deploy node_exporter service
  hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  become_user: azureuser
  timeout: 30 
  roles:
    - role: node_exporter
      state: present
